services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "80:80"
      # - "443:443"
    volumes:
      - ${BASE}/configs/adguard:/opt/adguardhome/conf
      - ${BASE}/appdata/adguard:/opt/adguardhome/work
    restart: unless-stopped