services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    ports:
      - "53:53/tcp"   # DNS ports
      - "53:53/udp"   # DNS ports
      # - "80:80"     # Web page access (without caddy)
      # - "443:443"
      # - "3000:3000" # Initial setup
    volumes:
      - ${BASE}/configs/adguard:/opt/adguardhome/conf
      - ${BASE}/appdata/adguard:/opt/adguardhome/work
    restart: unless-stopped
    healthcheck:
      # test: ["CMD-SHELL", "nslookup -type=a archlinux.org 127.0.0.1 || exit 1"]
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1/ || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
