services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
      - "443:443"
    volumes:
      - ../data/adguard:/opt/adguardhome/work
      - ../config/adguard:/opt/adguardhome/conf
    restart: unless-stopped