services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "80:80"
      # - "443:443"
    volumes:
      - ${BASE}/configs/adguard:/opt/adguardhome/conf
      - ${BASE}/appdata/adguard:/opt/adguardhome/work
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nslookup -type=a archlinux.org 127.0.0.1 || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s