services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"     # publish HTTP on the LXC host
      - "443:443"   # publish HTTPS on the LXC host
    volumes:
      - ../configs/caddy/Caddyfile:/etc/caddy/Caddyfile:ro  # Config file
      - ${BASE}/appdata/caddy/data:/data                    # Caddy's cert store (internal CA, certs, OCSP cache)
      - caddy_config:/config                                # Admin API state (optional but nice to persist)
      - ../web:/web:ro                                      # Local websites to serve
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "caddy", "validate", "--config", "/etc/caddy/Caddyfile"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-5s}
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-20s}