services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/caddy:/data
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
    environment:
      - CADDY_EMAIL=${CADDY_EMAIL}
      - CADDY_ACME_HTTP_PORT=80
      - CADDY_ACME_HTTPS_PORT=443
    networks:
      - asteria_network