services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    volumes:
      - ${BASE}/configs/homeassistant:/config
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 120s
