services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    # Remove port publishing - only accessible via Caddy
    # Re-added for now
    ports:
      - "9000:9000"
    environment:
      TZ: ${TZ}
      
      # Application Settings
      ALLOW_SIGNUP: "true"
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.lan
      
      # Database Settings (using SQLite by default)
      DB_ENGINE: sqlite
      
    volumes:
      - ${BASE}/appdata/mealie:/app/data
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:9000/api/app/about')"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-40s}
