services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ../../data/mosquitto:/mosquitto/data
      - ../../config/mosquitto:/mosquitto/config
    restart: unless-stopped