services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ${BASE}/appdata/mosquitto/data:/mosquitto/data
      - ${BASE}/appdata/mosquitto/log:/mosquitto/log
      # - ${BASE}/configs/mosquitto:/mosquitto/config
      - ../configs/mosquitto:/mosquitto/config:ro
    restart: unless-stopped
