# Logs are published to MQTT topics for monitoring:
# - Subscribe to $SYS/broker/log/# in Home Assistant to view all logs
# - Individual topics: $SYS/broker/log/E (errors), /W (warnings), /N (notices), /I (info)
# - Docker logs available via: docker logs mosquitto
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ../configs/mosquitto:/mosquitto/config:ro
      - ${BASE}/appdata/mosquitto/data:/mosquitto/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -h localhost -t '$$SYS/broker/version' -C 1 -W 15 >/dev/null 2>&1 || exit 1"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-20s}
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-20s}