services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    volumes:
      # Bind mount docker to allow it to access the Docker daemon socket
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BASE}/appdata/tailscale/portainer:/data
    environment:
      - TZ=${TZ}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s