services:
  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    network_mode: "host"                 # use host net stack
    cap_add:
      - NET_ADMIN                        # allow route/iptables tweaks
      - NET_RAW                          # allow raw sockets (ping)
    devices:
      - /dev/net/tun:/dev/net/tun        # tunnel device
    environment:
#      - TS_AUTHKEY=${TS_AUTHKEY}        # removed - use TS_AUTHKEY as env variable in up command
      - TS_HOSTNAME=${TS_HOSTNAME}
      - TS_ACCEPT_DNS=true
      - TS_EXTRA_ARGS=${TS_ARGS}         # e.g: --ssh --advertise-exit-node --advertise-routes=192.168.0.0/24
      - TS_STATE_DIR=/var/lib/tailscale  # Use persistent state directory
    volumes:
      - /var/run/tailscale:/var/run/tailscale
      - ${BASE}/appdata/tailscale:/var/lib/tailscale
      - ${BASE}/configs/tailscale:/etc/tailscale
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "tailscale", "status", "--peers=false"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - "com.centurylinklabs.watchtower.enable=false"