services:
  unbound:
    image: ${UNBOUND_IMAGE}
    container_name: unbound
    # Expose DNS to the LAN host
    # Ports not published as unbound is running internal-only
    ports:
      - "66:53/udp"   # DNS over UDP
      - "66:53/tcp"   # TCP fallback / large replies
    # Configs are read-only (:ro)
    volumes:
      # - ${BASE}/configs/unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro   # your unbound.conf, local records, etc.
      - ../configs/unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "drill", "@127.0.0.1", "cloudflare.com", "A"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-5s}
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-20s}
