services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    # Expose DNS to the LAN host
    ports:
      - "53:53/udp"   # DNS over UDP
      - "53:53/tcp"   # TCP fallback / large replies
    # Configs are read-only (:ro)
    volumes:
      - ${BASE}/configs/unbound:/opt/unbound/etc/unbound:ro   # your unbound.conf, local records, etc.
    restart: unless-stopped
    user: "1001:3001"
    profiles: ["serv"]
    healthcheck:
      test: ["CMD", "drill", "@127.0.0.1", "cloudflare.com", "A"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s