services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./data/uptime-kuma:/app/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite://data/uptime-kuma.db
      - SECRET_KEY=${UPTIME_KUMA_SECRET_KEY}
    networks:
      - asteria_network