services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      # Bind mount docker to allow it to access the Docker daemon socket
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Run at 5 AM daily (cron format)
      - WATCHTOWER_SCHEDULE=0 0 5 * * *
      # Clean up old images after updating
      - WATCHTOWER_CLEANUP=true
      # Include stopped containers in monitoring
      - WATCHTOWER_INCLUDE_STOPPED=true
      # Only monitor containers with label (optional, safer)
      # - WATCHTOWER_LABEL_ENABLE=true
      # Send notifications (optional)
      # - WATCHTOWER_NOTIFICATION_URL=discord://token@id
    healthcheck:
      test: ["CMD", "echo", "healthy"]
      interval: 6h
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped