const { createApp, ref, computed, onMounted } = Vue;

function hostFromUrl(u) {
  try { 
    return new URL(u).host;
  } catch (error) { 
    return ""; 
  }
}

createApp({
  setup() {
    const links = ref([]);
    const tableRows = ref([]);
    const updates = ref(null);
    const showCertModal = ref(false);

    // Only services Diun says have a newer image. Everything else is
    // noise on a dashboard you glance at.
    const pendingUpdates = computed(() =>
      (updates.value?.services ?? []).filter(s => s.status === "UPDATE")
    );

    const checkedAt = computed(() => {
      if (!updates.value?.generated) return "";
      return new Date(updates.value.generated).toLocaleString();
    });

    async function load() {
      try {
        const res = await fetch("services.json", { cache: "no-cache" });
        const items = await res.json();
        
        links.value = items.map(x => ({
          ...x, 
          host: hostFromUrl(x.href)
        }));
      } catch (error) {
        console.error('Error loading services:', error);
      }
    }

    async function loadTable() {
      try {
        const res = await fetch("services-table.json", { cache: "no-cache" });
        tableRows.value = await res.json();
      } catch (error) {
        console.error('Error loading services table:', error);
      }
    }

    // Generated by scripts/check-updates.sh --json on a systemd timer.
    // Absent until that has run at least once, which is a normal state
    // and must not break the rest of the page.
    // The Caddyfile ends with `try_files {path} /index.html`, so a missing
    // updates.json comes back as this page with a 200 and a JSON content
    // type, not a 404. Parsing throws on the HTML and the shape check
    // catches anything that somehow parses, leaving the panel hidden.
    async function loadUpdates() {
      try {
        const res = await fetch("updates.json", { cache: "no-cache" });
        if (!res.ok) return;
        const data = await res.json();
        if (!data || !Array.isArray(data.services)) return;
        updates.value = data;
      } catch (error) {
        console.debug('No update list yet:', error.message);
      }
    }

    async function downloadCertificate() {
      try {
        const response = await fetch('skypaw.crt');
        if (!response.ok) {
          throw new Error('Certificate file not found');
        }
        
        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        
        const a = document.createElement('a');
        a.href = url;
        a.download = 'skypaw.crt';
        a.style.display = 'none';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        
        // Clean up the blob URL
        window.URL.revokeObjectURL(url);
      } catch (error) {
        console.error('Error downloading certificate:', error);
        alert('Failed to download certificate. Please check if the file exists.');
      }
    }

    onMounted(() => {
      load();
      loadTable();
      loadUpdates();
    });

    return {
      links,
      tableRows,
      updates,
      pendingUpdates,
      checkedAt,
      showCertModal,
      downloadCertificate
    };
  }
}).mount("#app");